site_name: Diet
site_url: https://thuf.github.io/diet

theme:
  # favicon: /img/favicon.png
  # logo: /img/logo/dirigible-logo.png
  name: mkdocs
  # custom_dir: overrides
  features:
    - navigation.instant
    
# extra_css:
#   - stylesheets/custom.css
#   - stylesheets/homepage.css

markdown_extensions:
    - attr_list
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji
    - meta
    - footnotes
    - admonition
    - pymdownx.details

repo_url: https://github.com/thuf/diet
repo_name: thuf/diet
edit_uri: ../../thuf/diet/edit/diet/docs-site/docs/
